apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cmc-aat-ccd-importer-username
  namespace: money-claims-test
spec:
  encryptedData:
    key: AgAEDBwaaF84ketTZfRON8hFk1ocoq8dM9Lj6tVv9kZPNZdBY1cZXC6rb4RKABD5oIKKLnKKxpI6t36Bw8XBMU75RNzL+LQZCjCWjocKTgTtp1vAIpD+KejoFwvzKC9p6L1I8LcvYsJwb9NblEN1eBBWMRuoRjLxiYosHzqXDQcWoDIa+uDuaK9R7YW5Howq7clRZv9+zBjzTSStNV1vucqlWqsC/Q1+ngX6QrCyW+b6Z6dy6dp83ttG0rvrNSvLetgMIhtGmqr4IKihxZlmBN9HM0JI6Yx3OAHZzrI4qDzR1TWinI8wXh9nqNCXVz3nFoRQCDLTmTXfm9Bbxqa7Zrejl5W+0YSf9sTpqJe9q48wpXq5lUbFwACyIH5QycozVwf8wCNUPkQX+elsp7A630kdbLRf5a+Y4siI4Y8jT1FxO/TComO/yzNXkYLhPMEbHgD9xht7uFnJ0BWZaQjn7nzMVJKEz1Pcs6fSmyJn/QYnwo6VFbr7nDsLao1gfDTWed1ePNP8AE+biqcwG5YWiAHP/YGy5xkEOd0jReEHKoyryXKlOXNPS//VfHatiNnWJbIUijZz4XTxwuOisOt4R5SQvYiCa1UaJk7Z/e43cY7SKrSOyGl+kgSdQtGp0QROV8PjsNskMw3mHiYb+Kz6QZRTWKN/0u/rj0TibBjrLjciNPJmrp68EU1PTrSles+eiQFYDLU9f66nkPtvU+S0xH0yS7At5wO8EjRBMfs=

