apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cmc-aat-system-update-password
  namespace: money-claims-test
spec:
  encryptedData:
    key: AgAK7tt4IANpeR0sIUzgi3nEjfx7OInqnbAqp2/O56R3rAXoepXdSCZN7bUz0dcFvu6T9ZGMsyegbyrpGnGdAOgyZtyDCpmgSO+heaLYv+M7NAiPNANAseT34O//sAjB4OhFnDntRS33nMunpNeHH0bZgl9IuUbRUDHb/Lx+ee6lbgsnodhvvZL+LSJsRxe0rE0NBVnZPnCK8fQZjKKGQi1KMPdmaeGahxG/4m5P3e46gAbeRmgew7UCz5E0hsCTa7p0a8dT62tF6ifYIVIICsDaQVM7izjm1ljyJg7hLTzRyrmD5Xem02K+vTplpUUyw8+1LCGNDYFX621xSddG3iDT8AetcF9Co+gZTWcAOFz0y6DKdF+b3vc0rP4J1wUJ/xThEWAwXudNyj71dL3w5yUysXs7whhGrxMKRwniguJUCIG96r0us7+uPHHPOkJ9sIjBr9TlI9J3N+GoP+Z5XNRubCCwV+tkTnbRt/VBtDOlBXk2mENxP++MktKeaO75kVOKPGvRT0kuw4kOrCVgtL/3IPqMEzRO9rq9fcx4Nkc/KBT1eWT2MD7S+RIpxx0f7wZU0jO84VeYDg9c+ArgmEdUIGaf6h0rnt6+qJmfd8iRU2KQQq5f+H7WccW9m3Qq1/yrlJswEgEbFAm2L4HrqeCpgRoRyYCx7AEJMa0O4KosPcBgesMFPGNezfwqJU6GtTWVXmExdkQ4hnd8pZ8seVW1ZH8115u3P2lHW4von+YlVA==

