apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cmc-aat-anonymous-caseworker-password
  namespace: money-claims-test
spec:
  encryptedData:
    key: AgBzxFWmywaSS5wzbmp+xX2IAsyB9WHsXEIcmWFkatwq0hekH2DDB3NW3fk0jbFdi7RwNzXviSLrxOXoBAtf0xm/HCF+P1UrxI9r2rHytFVMn8z6srBV/DjbO6OZ1s957Jvxtga0Wsgm8p1YomqdBFjrR1SdAqB6G2/QBgrylyFBFjHxH4xh9ySMUra7cS4maoBjWmDc/YkhyNGKc6sxS2bwEKTC+ATFpcaKQlKy3xVy7F7lj+6+PDUGqmag6Abqh7K+qxdi4HV55GJpvDJhb+FKuzzIuhEIkEI44ZppbZZdb6ENZsUVVAQBsiPVr21jA93AX6T6QyWMtrkH2nJ7S1O9EdcQuqhy+nAMUCFpgAddlrdBk4mwiqnpTH4nlxiQ1v+Yk4d7sW7LgBbm5jm/Y3g9WpyydFSgYDB5BAj7aXmnMRw1n22H9uV7H4tXgFfLlPQ3foV4eoBCwZwpYgxgx6GRf53IekbrD/lL3YsXCk/GD9BsJft4xzSsUroqbdMu6Y4366kpxF+CTNOxOokSCFgPsvNphsf3tMz3HRnscQQsyovRlEQEEn+pC5j7rQLYANecyHZEBHNsu/AEJL+NylsiiDX6jsI/QYrumYt3UNTDUG5cvFcW0KGo4w+vy2xcILN77s08s+qbaRyl0qLCeD7soeG2D3Znc6zoteiZ7Lcb6qvwNp1fW/0Eb0PcpyhoytZ6uvD16WN3GMoWsM0sgt+AFGuDIKsTCLCJwfFyYs4i9g==

