apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cmc-aat-notify-api-key
  namespace: money-claims-test
spec:
  encryptedData:
    key: AgAqys14YR1QM7d+xUxcHNnvTkm9tStUEAcUoQiANqRyGCyacr+ojc8EolPL9hPB5z6J8XZraRB6YVcbA+qcawO+IakfBrKFbJUeXdywPGtsXaNjjdX3bD6nIxH0SWtXEqkYdrcs3xVtYLo59wsII3eRYjQZdNJL0cGOCsZ94BfLhPm4U0snppaQbkWnuBmU+U/tJwzrJoUEheg0ST8+BUXFY63t/tq6c+XjbnQgD429uGPG/pKWnjKXT76AmVs97UCB+UvGbFT8dYSs1iXbAOhwSPrL4mXpR+Ew3JQJP7XaWMx/jl0vpGnCgYK7W7nV0fMFm7aEn/Sl4skco+1aaH4DQO3XXjtUKz3fcvhqHDG4Z9EZ3J2e0F0HYETh7bKXqReGF2FZXulfXRYNGOa4jr1FRLyCjxKlpsxZOSOWDm9rKzdJmjPAmEmR2Z1K4pTlvirF0vqMy5H0ePs27oz9zePubZOyZbwxtkzabWCNkZOlvwSFkkh7coIOfox076De6/VZczGCqQVfLK9XykGM7W7ltOfZ6o0nBxahf6F0oICIEEJ6usfoUGGHwV2PagB1P4dnvuaOE3u8jU/7DNVJ3EnEjO3f4GXBRmXlLRqT3SMWU0aVy/fo0sM31b8A1Y3Yy6PAS0sJDbKsqzgbCLGvU3Q6Of9vpxhZmfEsXI7vLANZz5OBdrG3mogrb5mPptkxcCoq0S+4tUjgq9d4krfF5ijh9VxTCPtMt6ma0fYEusQFemPIrW+cpF7MB3qMnlzfdEIqEW4QYzV8oG8sqHuS+Rq8corD+2cBYZNA5sF6pacCN/E=

