name: chart-cmc pipeline
trigger:
  branches:
    include:
    - refs/tags/*
pr:
  branches:
    include:
    - master
resources:
  repositories:
  - repository: cnp-library
    type: github
    ref: master
    name: hmcts/cnp-azuredevops-libraries
    endpoint: 'hmcts'

jobs:
 - job: Validate
   pool:
     vmImage: 'Ubuntu 16.04'
   steps:
   - template: steps/charts/validate.yaml@cnp-library
     parameters:
       helmVersion: "2.14.3"
       chartName: cmc
       chartReleaseName: chart-cmc-ci-release
       chartNamespace: money-claims
       helmDeleteWait: "300"
       helmInstallWait: "300"
       helmInstallTimeout: "900"
       helmTestTimeout: "900"       

- job: Release
  # Make sure we have a tag to run this job
  condition: >
    and(
        succeeded(),
        startsWith(variables['Build.SourceBranch'], 'refs/tags/')
      )
  dependsOn: Validate
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - template: steps/charts/release.yaml@cnp-library
    parameters:
      helmVersion: "2.14.3"
      chartName: cmc
      chartReleaseName: chart-cmc
      chartNamespace: money-claims
