global:
  idamApiUrl: https://idam-api.aat.platform.hmcts.net
  idamWebUrl: idam-web-public.aat.platform.hmcts.net
  subscriptionId: "1c4f0704-a29e-403d-b719-b90c34ef14c9"
  tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
  ccdIngress: chart-cmc-ccd-release.service.core-compute-preview.internal
  cmcFrontendIngress: chart-cmc-citizen-frontend-release.service.core-compute-preview.internal
  devMode: true

### CMC SERVICES ###
cmc-claim-store:
  java:
    releaseNameOverride: "{{.Release.Name}}-claimstore"
    secrets:
      GOV_NOTIFY_API_KEY:
         disabled: true
      OAUTH2_CLIENT_SECRET:
         disabled: true
      IDAM_CASEWORKER_ANONYMOUS_USERNAME:
        disabled: true
      IDAM_CASEWORKER_ANONYMOUS_PASSWORD:
        disabled: true
      IDAM_CASEWORKER_SYSTEM_USERNAME:
        disabled: true
      IDAM_CASEWORKER_SYSTEM_PASSWORD:
        disabled: true
  ccd:
    ingressHost: "{{ .Values.global.ccdIngress }}"
    ingressIP: "10.97.17.51"
    consulIP: "10.97.11.254"
    idamApiUrl: "{{ .Values.global.idamApiUrl }}"
    idamWebUrl: "{{ .Values.global.idamWebUrl }}"
    apiGateway:
      s2sKey: AAAAAAAAAAAAAAAA
      idamClientSecret:
        fromSecret: false
    dataStoreApi:
      s2sKey: AAAAAAAAAAAAAAAA
    definitionStoreApi:
      s2sKey: AAAAAAAAAAAAAAAA
    adminWeb:
      s2sKey: AAAAAAAAAAAAAAAA
      idamClientSecret:
        fromSecret: false
    importer:
      userprofile:
        enabled: false
      definition:
        enabled: false

cmc-citizen-frontend:
  nodejs:
    ingressHost: "{{ .Values.global.cmcFrontendIngress }}"
    releaseNameOverride: "{{.Release.Name}}-cmc-citizen-web"
    secrets:
      OAUTH_CLIENT_SECRET:
        disabled: true
  idam-pr:
    service:
      redirect_uri: "{{ .Values.global.cmcFrontendIngress }}/receiver"
  rpe-feature-toggle-api:
    importer:
      apiUrl: "http://{{.Release.Name}}-ftrtgl/api/ff4j/store/features/"
    java:
      releaseNameOverride: "{{.Release.Name}}-ftrtgl"

########################

##### DEPENDENCIES #####
rpe-send-letter-service:
  java:
    releaseNameOverride: "{{.Release.Name}}-sendletter"

dm-store:
  java:
    releaseNameOverride: "{{.Release.Name}}-dmstore"

cmc-pdf-service:
  java:
    releaseNameOverride: "{{.Release.Name}}-pdf"

draft-store-service:
  java:
    releaseNameOverride: "{{.Release.Name}}-draftstore"

fees-register-api:
  java:
    releaseNameOverride: "{{.Release.Name}}-fees"

payment-api:
  java:
    releaseNameOverride: "{{.Release.Name}}-payments"
    secrets:
      GOV_PAY_AUTH_KEY_CMC:
          disabled: true

rpe-service-auth-provider:
  java:
    releaseNameOverride: "{{.Release.Name}}-s2s"

postgresql:
  nameOverride: postgres
########################
