  
global:
  idamApiUrl: https://idam-api.aat.platform.hmcts.net
  idamWebUrl: idam-web-public.aat.platform.hmcts.net
  devMode: true

### CMC SERVICES ###
cmc-claim-store:
  java:
    releaseNameOverride: demo-preview-cmc-claimstore
    secrets: 
      GOV_NOTIFY_API_KEY:
         disabled: true
      OAUTH2_CLIENT_SECRET:
         disabled: true
      IDAM_CASEWORKER_ANONYMOUS_USERNAME:
        disabled: true
      IDAM_CASEWORKER_ANONYMOUS_PASSWORD:
        disabled: true
      IDAM_CASEWORKER_SYSTEM_USERNAME:
        disabled: true
      IDAM_CASEWORKER_SYSTEM_PASSWORD:
        disabled: true
  ccd:
    ingressHost: cmc-ccd-{{.Release.Name}}.service.core-compute-preview.internal
    #idamApiUrl: https://idam-api.aat.platform.hmcts.net
    #idamWebUrl: https://idam-web-public.aat.platform.hmcts.net
    s2sUrl: http://{{.Release.Name}}-s2s
    draftStoreUrl: http://{{.Release.Name}}-draftstore
    paymentsUrl: http://{{.Release.Name}}-payments
    apiGateway:
      s2sKey: AAAAAAAAAAAAAAAA
      idamClientSecret: 
        fromSecret: true
        secretKeyRefName: ccd-aat-ccd-api-gateway-oauth2-client-secret
        secretKeyRefKey: key
    dataStoreApi:
      s2sKey: AAAAAAAAAAAAAAAA
    definitionStoreApi:
      s2sKey: AAAAAAAAAAAAAAAA
    adminWeb:
      s2sKey: AAAAAAAAAAAAAAAA
      idamClientSecret: 
        fromSecret: true
        secretKeyRefName: ccd-aat-ccd-admin-web-oauth2-client-secret
        secretKeyRefKey: key
    idam-pr:
      releaseNameOverride: {{.Release.Name}}-ccd-idam-pr
      redirect_uris:
        CCD:
          - https://case-management-web-cmc-ccd-{{.Release.Name}}.service.core-compute-preview.internal/oauth2redirect
        CCD Admin:
          - https://admin-web-cmc-ccd-{{.Release.Name}}.service.core-compute-preview.internal/oauth2redirect
    importer:
      userprofile:
        userProfileDatabaseHost: {{.Release.Name}}-postgres
      definition:
        importerFromSecret: true
        importerUsername: 
          secretKeyRefName: cmc-aat-ccd-importer-username
          secretKeyRefKey: key
        importerPassword: 
          secretKeyRefName: cmc-aat-ccd-importer-password
          secretKeyRefKey: key
        redirectUri: https://ccd-case-management-web-aat.service.core-compute-aat.internal/oauth2redirect
    postgresql:
      nameOverride: postgres

cmc-citizen-frontend:
  nodejs:
    ingressHost: cmc-citizen-frontend-{{.Release.Name}}.service.core-compute-preview.internal
    memoryRequests: 512Mi
    memoryLimits: 1024Mi 
    releaseNameOverride: {{.Release.Name}}-cmc-citizen-web
    secrets:
      OAUTH_CLIENT_SECRET:
        disabled: true

  idam-pr:
    service:
      redirect_uri: https://cmc-citizen-frontend-{{.Release.Name}}.service.core-compute-preview.internal/receiver
  rpe-feature-toggle-api:
    importer:
      apiUrl: http://{{.Release.Name}}-ftrtgl/api/ff4j/store/features/
    java:
      releaseNameOverride: {{.Release.Name}}-ftrtgl

########################

##### DEPENDENCIES #####
rpe-send-letter-service:
  java:
    releaseNameOverride: {{.Release.Name}}-sendletter

dm-store:
  java:
    releaseNameOverride: {{.Release.Name}}-dmstore

cmc-pdf-service:
  java:
    releaseNameOverride: {{.Release.Name}}-pdf

draft-store-service:
  java:
    releaseNameOverride: {{.Release.Name}}-draftstore

fees-register-api:
  java:
    releaseNameOverride: {{.Release.Name}}-fees

payment-api:
  java:
    releaseNameOverride: {{.Release.Name}}-payments
    secrets: 
      GOV_PAY_AUTH_KEY_CMC:
          disabled: true

rpe-service-auth-provider:
  java:
    releaseNameOverride: {{.Release.Name}}-s2s

postgresql:
  nameOverride: postgres
########################
