global:
  devMode: true
  environment: "aat"
  idamApiUrl: "https://idam-api.aat.platform.hmcts.net"
  idamWebUrl: "https://idam-web-public.aat.platform.hmcts.net"
  pdfServiceUrl: "http://cmc-pdf-service-aat.service.core-compute-aat.internal"
  sendLetterUrl: "http://rpe-send-letter-service-aat.service.core-compute-aat.internal"
  documentManagementUrl: "http://dm-store-aat.service.core-compute-aat.internal"
  dgAssemblyUrl: "http://dg-docassembly-aat.service.core-compute-aat.internal"
  ccdCaseDataApiUrl: "http://ccd-data-store-api-aat.service.core-compute-aat.internal"
  s2sAuthUrl: "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
  draftStoreUrl: "http://draft-store-service-aat.service.core-compute-aat.internal"
  paymentUrl: "http://payment-api-aat.service.core-compute-aat.internal"
  feesUrl: "http://fees-register-api-aat.service.core-compute-aat.internal"
  togglesUrl: "http://chart-cmc-ci-test-rpe-feature-toggle-api-java"
  cmcBackendUrl: "http://chart-cmc-ci-test-java"
  postgresqlHost: "chart-cmc-ci-test-postgresql"

### CMC SERVICES ###
cmc-claim-store:
  java:
    environment:
      FRONTEND_BASE_URL: "https://chart-cmc-ci-test-frontend.service.core-compute-preview.internal"
      RESPOND_TO_CLAIM_URL: "https://chart-cmc-ci-test-frontend.service.core-compute-preview.internal/first-contact/start"

cmc-citizen-frontend:
  nodejs:
    ingressHost: "chart-cmc-ci-test-frontend.service.core-compute-preview.internal"
  idam-pr:
    service:
      redirect_uri: "https://chart-cmc-ci-test-frontend.service.core-compute-preview.internal/receiver"
  rpe-feature-toggle-api:
    importer:
      apiUrl: "http://chart-cmc-ci-test-rpe-feature-toggle-api/api/ff4j/store/features/"
    java:
      releaseNameOverride: "chart-cmc-ci-test-rpe-feature-toggle-api"
      environment:
        FEATURES_DB_HOST: "chart-cmc-ci-test-postgresql"

postgresql:
  persistence:
    enabled: false
