dependencies:
  - name: postgresql
    version: ~3.1.0
    repository: '@stable'
  - name: cmc-claim-store
    version: ~0.0.8
    repository: '@hmcts'
  - name: cmc-citizen-frontend
    version: ~0.0.5
    repository: '@hmcts'
  - name: draft-store-service
    version: ~0.0.3
    repository: '@hmcts'
  - name: rpe-service-auth-provider
    version: ~0.0.2
    repository: '@hmcts'
  - name: cmc-pdf-service
    version: ~0.1.0
    repository: '@hmcts'
  - name: fees-register-api
    version: ~0.0.3
    repository: '@hmcts'
  - name: payment-api
    version: ~0.0.3
    repository: '@hmcts'
  - name: dm-store
    version: ~0.0.1
    repository: '@hmcts'
  - name: rpe-send-letter-service
    version: ~0.0.3
    repository: '@hmcts'
