dependencies:
  - name: postgresql
    version: ~5.3.0
    repository: '@stable'
  - name: cmc-claim-store
    version: ~3.0.0
    repository: '@hmctspublic'
  - name: cmc-citizen-frontend
    version: ~2.0.1
    repository: '@hmctspublic'
