dependencies:
  - name: postgresql
    version: ~6.3.5
    repository: '@stable'

  - name: cmc-claim-store
    version: ~4.1.9
    repository: '@hmctspublic'

  - name: cmc-citizen-frontend
    version: ~3.3.7
    repository: '@hmctspublic'
