dependencies:
  - name: postgresql
    version: ~5.3.0
    repository: '@stable'
  - name: cmc-claim-store
    version: ~1.1.0
    repository: '@hmcts'
  - name: cmc-citizen-frontend
    version: ~1.0.1
    repository: '@hmcts'
  - name: draft-store-service
    version: ~1.0.3
    repository: '@hmcts'
  - name: rpe-service-auth-provider
    version: ~0.0.5
    repository: '@hmcts'
  - name: cmc-pdf-service
    version: ~0.1.3
    repository: '@hmcts'
  - name: fees-register-api
    version: ~0.0.4
    repository: '@hmcts'
  - name: payment-api
    version: ~0.0.4
    repository: '@hmcts'
  - name: dm-store
    version: ~1.0.1
    repository: '@hmcts'
  - name: rpe-send-letter-service
    version: ~0.0.4
    repository: '@hmcts'
