dependencies:
  - name: postgresql
    version: ~5.3.0
    repository: '@stable'

  - name: cmc-claim-store
    version: ~3.1.0
    repository: '@hmctspublic'

  - name: cmc-citizen-frontend
    version: ~3.2.0
    repository: '@hmctspublic'
