### CMC SERVICES ###
cmc-claim-store:
  java:
    releaseNameOverride: "chart-cmc-preview-claimstore"
    secrets:
      GOV_NOTIFY_API_KEY:
        secretRef: notify-api-key
        key: key
      OAUTH2_CLIENT_SECRET:
        secretRef: oauth-client-secret
        key: key
      IDAM_CASEWORKER_ANONYMOUS_USERNAME:
        secretRef: anonymous-caseworker-username
        key: key
      IDAM_CASEWORKER_ANONYMOUS_PASSWORD:
        secretRef: anonymous-caseworker-password
        key: key
      IDAM_CASEWORKER_SYSTEM_USERNAME:
        secretRef: system-update-username
        key: key
      IDAM_CASEWORKER_SYSTEM_PASSWORD:
        secretRef: system-update-password
        key: key
    environment:
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025
      CLAIM_STORE_DB_HOST: "chart-cmc-preview-postgres"
      CMC_DB_HOST: "chart-cmc-preview-postgres"
      CORE_CASE_DATA_API_URL: "http://chart-cmc-preview-data-store-api"
      FEATURE_TOGGLES_DIRECTIONS_QUESTIONNAIRE_ENABLED: true
      FEATURE_TOGGLES_SAVE_CLAIM_STATE_ENABLED: true
      IDAM_API_URL: "https://idam-api.aat.platform.hmcts.net"
      IDAM_S2S_AUTH_URL: "http://chart-cmc-preview-s2s"
      PDF_SERVICE_URL: "http://chart-cmc-preview-pdf"
      SEND_LETTER_URL: "http://chart-cmc-preview-sendletter"
      DOCUMENT_MANAGEMENT_URL: "http://chart-cmc-preview-dmstore"
      DOC_ASSEMBLY_URL: "http://chart-cmc-preview-dg-docassembly"
      FRONTEND_BASE_URL: "https://chart-cmc-preview-citizen-frontend.service.core-compute-preview.internal"
      RESPOND_TO_CLAIM_URL: "https://chart-cmc-preview-citizen-frontend.service.core-compute-preview.internal/first-contact/start"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST: mailhog
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: false
      APPINSIGHTS_INSTRUMENTATIONKEY: 00000000-0000-0000-0000-000000000000
      PAY_URL: "http://chart-cmc-preview-payments"
      FEES_URL: "http://chart-cmc-preview-fees"

  ccd:
    ingressHost: "cmc-ccd-chart.service.core-compute-preview.internal"
    idamApiUrl: "https://idam-api.aat.platform.hmcts.net"
    idamWebUrl: "https://idam-web-public.aat.platform.hmcts.net"
    s2sUrl: "http://chart-cmc-preview-s2s"
    draftStoreUrl: "http://chart-cmc-preview-draftstore"
    paymentsUrl: "http://chart-cmc-preview-payments"
    apiGateway:
      s2sKey: AAAAAAAAAAAAAAAA
      idamClientSecret:
        fromSecret: true
        secretKeyRefName: ccd-api-gateway-oauth2-client-secret
        secretKeyRefKey: key
    dataStoreApi:
      s2sKey: AAAAAAAAAAAAAAAA
    definitionStoreApi:
      s2sKey: AAAAAAAAAAAAAAAA
    adminWeb:
      enabled: false
    caseManagementWeb:
      enabled: false
    idam-pr:
      api:
        url: "https://idam-api.aat.platform.hmcts.net"
      web_public:
        url: "https://idam-web-public.aat.platform.hmcts.net"
      releaseNameOverride: "chart-cmc-preview-ccd-idam-pr"
      redirect_uris:
        CCD:
          - "https://chart-cmc-preview-case-management-web.service.core-compute-preview.internal/oauth2redirect"
        CCD Admin:
          - "https://chart-cmc-preview-admin-web-ccd.service.core-compute-preview.internal/oauth2redirect"
    importer:
      userprofile:
        userProfileDatabaseHost: "chart-cmc-preview-postgres"
      definition:
        importerFromSecret: true
        importerUsername:
          secretKeyRefName: ccd-importer-username
          secretKeyRefKey: key
        importerPassword:
          secretKeyRefName: ccd-importer-password
          secretKeyRefKey: key
        redirectUri: "https://ccd-case-management-web-aat.service.core-compute-aat.internal/oauth2redirect"
    postgresql:
      nameOverride: postgres

cmc-citizen-frontend:
  nodejs:
    ingressHost: "chart-cmc-preview-citizen-frontend.service.core-compute-preview.internal"
    memoryRequests: 512Mi
    memoryLimits: 1024Mi
    releaseNameOverride: "chart-cmc-preview-citizen-web"
    secrets:
      OAUTH_CLIENT_SECRET:
        secretRef: citizen-oauth-client-secret
        key: key
    environment:
      IDAM_API_URL: "https://idam-api.aat.platform.hmcts.net"
      IDAM_AUTHENTICATION_WEB_URL: "https://idam-web-public.aat.platform.hmcts.net"
      FEATURE_TOGGLES_API_URL: "http://chart-cmc-preview-ftrtgl"
      CLAIM_STORE_URL: "http://chart-cmc-preview-claimstore"
      IDAM_S2S_AUTH: "http://chart-cmc-preview-s2s"
      PAY_URL: "http://chart-cmc-preview-payments"
      FEES_URL: "http://chart-cmc-preview-fees"
      DRAFT_STORE_URL: "http://chart-cmc-preview-draftstore"
      FEATURE_MEDIATION: true
      FEATURE_MEDIATION_PILOT: true
      FEATURE_DIRECTIONS_QUESTIONNAIRE: true
      FEATURE_ADMISSIONS: true
      FEATURE_INVERSION_OF_CONTROL: true

  idam-pr:
    service:
      redirect_uri: "https://chart-cmc-preview-citizen-frontend.service.core-compute-preview.internal/receiver"
  rpe-feature-toggle-api:
    importer:
      apiUrl: "http://chart-cmc-preview-ftrtgl/api/ff4j/store/features/"
    java:
      releaseNameOverride: "chart-cmc-preview-ftrtgl"
      environment:
        FEATURES_DB_HOST: "chart-cmc-preview-postgres"
########################

##### DEPENDENCIES #####
rpe-send-letter-service:
  java:
    releaseNameOverride: "chart-cmc-preview-sendletter"
    environment:
      FLYWAY_URL: "jdbc:postgresql://chart-cmc-preview-postgres:5432/send_letter"
      LETTER_TRACKING_DB_HOST: "chart-cmc-preview-postgres"
      S2S_URL: "http://chart-cmc-preview-s2s"

dm-store:
  java:
    releaseNameOverride: "chart-cmc-preview-dmstore"
    environment:
      IDAM_USER_BASE_URI: "https://idam-api.aat.platform.hmcts.net"
      IDAM_S2S_BASE_URI: "http://chart-cmc-preview-s2s"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://chart-cmc-preview-postgres:5432/evidence"

cmc-pdf-service:
  java:
    releaseNameOverride: "chart-cmc-preview-pdf"

draft-store-service:
  java:
    releaseNameOverride: "chart-cmc-preview-draftstore"
    environment:
      IDAM_URL: "https://idam-api.aat.platform.hmcts.net"
      S2S_URL: "http://chart-cmc-preview-s2s"
      DRAFT_STORE_DB_HOST: "chart-cmc-preview-postgres"

fees-register-api:
  java:
    releaseNameOverride: "chart-cmc-preview-fees"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://chart-cmc-preview-postgres:5432/fees_register"

payment-api:
  java:
    releaseNameOverride: "chart-cmc-preview-payments"
    secrets:
      GOV_PAY_AUTH_KEY_CMC:
        secretRef: "gov-pay-keys-cmc"
        key: key
    environment:
      AUTH_IDAM_CLIENT_BASEURL: "https://idam-api.aat.platform.hmcts.net"
      AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: "http://chart-cmc-preview-s2s"
      FEES_REGISTER_URL: "http://chart-cmc-preview-fees"
      CORE_CASE_DATA_API_URL: "http://chart-cmc-preview-data-store-api"
      CCD_CLIENT_URL: "http://chart-cmc-preview-data-store-api"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://chart-cmc-preview-postgres:5432/payment_api"
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025

rpe-service-auth-provider:
  java:
    releaseNameOverride: "chart-cmc-preview-s2s"

dg-docassembly:
  docassembly-api:
    java:
      releaseNameOverride: "chart-cmc-preview-dg-docassembly"
    environment:
      DM_STORE_APP_URL: "http://chart-cmc-preview-dmstore"
      IDAM_API_BASE_URI: "https://idam-api.aat.platform.hmcts.net"
      S2S_BASE_URI: "http://chart-cmc-preview-s2s"
      DOCMOSIS_TEMPLATES_ENDPOINT: https://docmosis-development.platform.hmcts.net
      DOCMOSIS_ENDPOINT: https://docmosis-development.platform.hmcts.net/rs/render

postgresql:
  nameOverride: postgres

########################
