tags:
  idam-pr: true   # citizen-frontend chart - will add IDAM redirect urls

global:
  devMode: true
  idamApiUrl: ""
  idamWebUrl: ""
  cmcFrontendUrl: ""
  cmcBackendUrl: ""
  draftStoreUrl: ""
  s2sAuthUrl: ""
  pdfServiceUrl: ""
  paymentUrl: ""
  feesUrl: ""
  sendLetterUrl: ""
  documentManagementUrl: ""
  dgAssemblyUrl: ""
  ccdCaseDataApiUrl: ""
  postgresqlHost: ""

### CMC SERVICES ###
cmc-claim-store:
  java:
    keyVaults:
    secrets:
      GOV_NOTIFY_API_KEY:
        secretRef: notify-api-key
        key: key
      OAUTH2_CLIENT_SECRET:
        secretRef: oauth-client-secret
        key: key
      IDAM_CASEWORKER_ANONYMOUS_USERNAME:
        secretRef: anonymous-caseworker-username
        key: key
      IDAM_CASEWORKER_ANONYMOUS_PASSWORD:
        secretRef: anonymous-caseworker-password
        key: key
      IDAM_CASEWORKER_SYSTEM_USERNAME:
        secretRef: system-update-username
        key: key
      IDAM_CASEWORKER_SYSTEM_PASSWORD:
        secretRef: system-update-password
        key: key
      RPA_NOTIFICATIONS_MORETIMEREQUESTEDRECIPIENT:
        secretRef: rpa-email-more-time-requested
        key: key
      RPA_NOTIFICATIONS_SEALEDCLAIMRECIPIENT:
        secretRef: rpa-email-sealed-claim
        key: key
      RPA_NOTIFICATIONS_PAIDINFULLRECIPIENT:
        secretRef: rpa-email-paid-in-full
        key: key
      RPA_NOTIFICATIONS_COUNTYCOURTJUDGEMENTRECIPIENT:
        secretRef: rpa-email-ccj
        key: key
      RPA_NOTIFICATIONS_RESPONSERECIPIENT:
        secretRef: rpa-email-response
        key: key
      STAFF_NOTIFICATIONS_RECIPIENT:
        secretRef: staff-email
        key: key
      LIVE_SUPPORT_RECIPIENT:
        secretRef: live-support-email
        key: key
      LAUNCH_DARKLY_SDK_KEY:
        secretRef: launchdarkly-sdk-key
        key: key
    image: hmctspublic.azurecr.io/cmc/claim-store:latest
    environment:
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST: mailhog
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: false
      CMC_DB_HOST: "{{ .Values.global.postgresqlHost }}"
      CMC_DB_USERNAME: hmcts
      CMC_DB_PASSWORD: hmcts
      CMC_DB_CONNECTION_OPTIONS: '?sslmode=allow'
      IDAM_API_URL: '{{ .Values.global.idamApiUrl }}'
      IDAM_S2S_AUTH_URL: '{{ .Values.global.s2sAuthUrl }}'
      CORE_CASE_DATA_API_URL: '{{ .Values.global.ccdCaseDataApiUrl }}'
      PDF_SERVICE_URL: '{{ .Values.global.pdfServiceUrl }}'
      SEND_LETTER_URL: '{{ .Values.global.sendLetterUrl }}'
      DOCUMENT_MANAGEMENT_URL: '{{ .Values.global.documentManagementUrl }}'
      DOC_ASSEMBLY_URL: '{{ .Values.global.dgAssemblyUrl }}'
      LIVE_SUPPORT_SENDER: noreply@reform.hmcts.net
      STAFF_NOTIFICATIONS_SENDER: noreply@reform.hmcts.net
      PAY_URL: '{{ .Values.global.paymentUrl }}'
      FEES_URL: '{{ .Values.global.feesUrl }}'
    readinessDelay: 180
    livenessDelay: 180
    readinessPeriod: 60
    livenessPeriod: 60

cmc-citizen-frontend:
  nodejs:
    image: hmctspublic.azurecr.io/cmc/citizen-frontend:latest
    memoryRequests: 512Mi
    memoryLimits: 1024Mi
    readinessDelay: 180
    livenessDelay: 180
    readinessPeriod: 60
    livenessPeriod: 60
    keyVaults:
    secrets:
      OAUTH_CLIENT_SECRET:
        secretRef: citizen-oauth-client-secret
        key: key
        disabled: false
      POSTCODE_LOOKUP_API_KEY:
        secretRef: os-postcode-lookup-api-key
        key: key
        disabled: false
      LAUNCH_DARKLY_SDK_KEY:
        secretRef: launchdarkly-sdk-key
        key: key
        disabled: false
    environment:
      IDAM_API_URL: '{{ .Values.global.idamApiUrl }}'
      IDAM_AUTHENTICATION_WEB_URL: '{{ .Values.global.idamWebUrl }}'
      CLAIM_STORE_URL: '{{ .Values.global.cmcBackendUrl }}'
      IDAM_S2S_AUTH: '{{ .Values.global.s2sAuthUrl }}'
      DRAFT_STORE_URL: '{{ .Values.global.draftStoreUrl }}'
      FEATURE_MEDIATION: true
      FEATURE_MEDIATION_PILOT: true
      FEATURE_DIRECTIONS_QUESTIONNAIRE: true
      FEATURE_ADMISSIONS: true
      FEATURE_INVERSION_OF_CONTROL: true
      PAY_URL: '{{ .Values.global.paymentUrl }}'
      FEES_URL: '{{ .Values.global.feesUrl }}'
  idam-pr:
    service:
      name: Money Claims - Citizen

########################

postgresql:
  resources:
    requests:
      cpu: 25m
  initdbScripts:
    init.sql: |-
      CREATE DATABASE "claimstore" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "cmc" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
  postgresqlUsername: hmcts
  postgresqlPassword: hmcts
  persistence:
    enabled: true

########################
