tags:
  cmc-claim-store-postgresql-pod: false # claim-store chart
  cmc-citizen-frontend-pod: false       # claim-store chart
  cmc-ccd-stack: true                   # claim-store chart
  idam-pr: false                        # manually configure whitelists in IDAM until IDAM here
  ccd-idam-pr: false                    # manually configure whitelists in IDAM until IDAM here
  rpe-feature-toggle-api-pod: true      # citizen-frontend dep
  postgresql-pod: false                 # any chart specific postgres
  blobstorage: true                     # blob storage for dm-store

### CMC SERVICES ###
cmc-claim-store:
  java:
    image: hmcts.azurecr.io/hmcts/cmc-claim-store:latest
    environment:
      CLAIM_STORE_DB_USERNAME: hmcts
      CLAIM_STORE_DB_PASSWORD: hmcts
      CMC_DB_USERNAME: hmcts
      CMC_DB_PASSWORD: hmcts
  ccd:
    adminWeb:
      enabled: true  # not sure why not picked up from claim-store defaults, missing version bump prob?
      environment:
        NODE_TLS_REJECT_UNAUTHORIZED: 0  # not sure why not picked up from claim-store defaults, missing version bump prob?
    caseManagementWeb:
      enabled: true  # not sure why not picked up from claim-store defaults, missing version bump prob?
      environment:
        NODE_TLS_REJECT_UNAUTHORIZED: 0  # not sure why not picked up from claim-store defaults, missing version bump prob?

cmc-citizen-frontend:
  nodejs:
    image: hmcts.azurecr.io/hmcts/cmc-citizen-frontend:latest
    registerAdditionalDns:
      enabled: false
  rpe-feature-toggle-api:
    java:
      environment:
        FEATURES_DB_NAME: features
        FEATURES_DB_USER_NAME: hmcts
        FEATURES_DB_PASSWORD: hmcts
########################

##### DEPENDENCIES #####
rpe-send-letter-service:
  java:
    image: hmcts.azurecr.io/hmcts/rpe-send-letter-service:latest
    environment:
      FILE_CLEANUP_ENABLED: true
      LETTER_TRACKING_DB_CONN_OPTIONS: ""
      LETTER_TRACKING_DB_NAME: send_letter
      LETTER_TRACKING_DB_USER_NAME: "hmcts"
      LETTER_TRACKING_DB_PASSWORD: "hmcts"

dm-store:
  java:
    image: hmcts.azurecr.io/hmcts/dm-store:latest
    secrets:
      STORAGE_ACCOUNT_NAME:
        disabled: true
      STORAGE_ACCOUNT_KEY:
        disabled: true
      STORAGE_CONTAINER_DOCUMENT_CONTAINER_NAME:
        disabled: true
    keyVaults:
    environment:
      ENABLE_DB_MIGRATE: 'true'
      ENABLE_TTL: 'false'
      SPRING_DATASOURCE_USERNAME: hmcts
      SPRING_DATASOURCE_PASSWORD: hmcts

cmc-pdf-service:
  java:
    image: hmcts.azurecr.io/hmcts/cmc-pdf-service:latest
    keyVaults:

draft-store-service:
  java:
    image: hmcts.azurecr.io/hmcts/draft-store-service:latest
    keyVaults:
    environment:
      DRAFT_STORE_DB_NAME: draftstore
      DRAFT_STORE_DB_PORT: '5432'
      DRAFT_STORE_DB_USER_NAME: hmcts
      RUN_DB_MIGRATION_ON_STARTUP: 'true'
      DRAFT_STORE_DB_PASSWORD: hmcts

fees-register-api:
  java:
    image: hmcts.azurecr.io/hmcts/fees-register-api:latest
    keyVaults:
    environment:
      SPRING_DATASOURCE_USERNAME: hmcts
      SPRING_DATASOURCE_PASSWORD: hmcts
      SPRING_LIQUIBASE_ENABLED: true
      ENABLE_FEE_LOADER: true

payment-api:
  java:
    image: hmcts.azurecr.io/hmcts/payment-api:latest
    keyVaults:
    environment:
      SPRING_DATASOURCE_USERNAME: hmcts
      SPRING_DATASOURCE_PASSWORD: hmcts
      SPRING_LIQUIBASE_ENABLED: true

rpe-service-auth-provider:
  java:
    image: hmcts.azurecr.io/hmcts/rpe-service-auth-provider:latest
    keyVaults:
    environment:
      MICROSERVICEKEYS_CMC: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_CMC_CLAIM_SUBMIT_API: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_CMC_LEGAL_FRONTEND: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_CMC_CLAIM_STORE: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_EM_GW: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_CCD_DATA: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_CCD_DEFINITION: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_CCD_GATEWAY: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_DG_DOCASSEMBLY_API: AAAAAAAAAAAAAAAA

postgresql:
  resources:
    requests:
      cpu: 25m
  initdbScripts:
    init.sql: |-
      CREATE DATABASE "claimstore" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "cmc" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "features" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "draftstore" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "fees_register" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "payment_api" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "evidence" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "send_letter" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "data-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "definition-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
  postgresqlUsername: hmcts
  postgresqlPassword: hmcts
  postgresqlDatabase: user-profile
  persistence:
    enabled: false
########################