tags:
  cmc-claim-store-postgresql-pod: false # claim-store chart
  cmc-citizen-frontend-pod: false       # claim-store chart
  cmc-claim-store-pod: false            # claim-store pod from citizen-frontend chart
  cmc-ccd-stack: false                  # claim-store chart
  frontend-ccd-stack: false             # disable citizen-frontend chart ccd stack
  idam-pr: true                         # citizen-frontend chart - will add IDAM redirect urls
  rpe-feature-toggle-api-pod: true      # citizen-frontend dep

### CMC SERVICES ###
cmc-claim-store:
  java:
    image: hmctspublic.azurecr.io/cmc/claim-store:latest
    readinessDelay: 180
    livenessDelay: 180
    readinessPeriod: 60
    livenessPeriod: 60
    keyVaults:
    environment:
      CMC_DB_USERNAME: hmcts
      CMC_DB_PASSWORD: hmcts
      PAY_URL: false
      FEES_URL: false

cmc-citizen-frontend:
  nodejs:
    image: hmctspublic.azurecr.io/cmc/citizen-frontend:latest
    memoryRequests: 512Mi
    memoryLimits: 1024Mi
    readinessDelay: 180
    livenessDelay: 180
    readinessPeriod: 60
    livenessPeriod: 60
    keyVaults:
    environment:
      IDAM_S2S_TOTP_SECRET: AAAAAAAAAAAAAAAA
  idam-pr:
    service:
      name: Money Claims - Citizen
  rpe-feature-toggle-api:
    java:
      readinessDelay: 180
      livenessDelay: 180
      readinessPeriod: 60
      livenessPeriod: 60
      keyVaults:
      environment:
        FEATURES_DB_NAME: features
        FEATURES_DB_USER_NAME: hmcts
        FEATURES_DB_PASSWORD: hmcts
        ADMIN_USERNAME_TEST: admin@example.com
        ADMIN_PASSWORD_TEST: Password
        EDITOR_USERNAME_TEST: editor@example.com
        EDITOR_PASSWORD_TEST: Password
    importer:
      adminUsername: admin@example.com
      adminPassword: Password
      cron:
        enabled: false
      oneoff:
        command: /scripts/add-weighted-toggle.sh cmc_admissions 'CMC admissions' '1.0' &&
          /scripts/add-weighted-toggle.sh cmc_directions_questionnaire 'CMC Directions Questionnaire' '1.0' &&
          /scripts/add-weighted-toggle.sh cmc_mediation_pilot 'CMC Mediation Pilot' '1.0' &&
          /scripts/add-weighted-toggle.sh cmc_legal_advisor 'CMC LEGAL ADVISOR' '1.0' &&
          /scripts/add-weighted-toggle.sh cmc_judge_pilot 'CMC Judge Pilot' '1.0' &&
          /scripts/add-toggle.sh cmc_defence_reminders 'CMC defence reminders' false
        enabled: true
        permissions: cmc-new-features-consent-given

########################

postgresql:
  resources:
    requests:
      cpu: 25m
  initdbScripts:
    init.sql: |-
      CREATE DATABASE "cmc" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "features" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
  postgresqlUsername: hmcts
  postgresqlPassword: hmcts
  postgresqlDatabase: claimstore
  persistence:
    enabled: true

########################
