tags:
  cmc-claim-store-postgresql-pod: false # claim-store chart
  cmc-citizen-frontend-pod: false # claim-store chart
  rpe-feature-toggle-api-pod: true # citizen-frontend dep
  postgresql-pod: false # any chart specific postgres

cmc-pdf-service:
  java:
    releaseNameOverride: cmc-pdf-service
    image: hmcts.azurecr.io/hmcts/cmc-pdf-service:latest

draft-store-service:
  java:
    releaseNameOverride: draft-store-service
    image: hmcts.azurecr.io/hmcts/draft-store-service:latest
    environment:
      IDAM_URL: https://idam-api.aat.platform.hmcts.net
      S2S_URL: http://rpe-service-auth-provider
      DRAFT_STORE_DB_HOST: cmc-postgres
      DRAFT_STORE_DB_NAME: draftstore
      DRAFT_STORE_DB_PORT: '5432'
      DRAFT_STORE_DB_USER_NAME: draftstore
      RUN_DB_MIGRATION_ON_STARTUP: 'true'
      DRAFT_STORE_DB_PASSWORD: draftstore

fees-register-api:
  java:
    releaseNameOverride: fees-register-api
    image: hmcts.azurecr.io/hmcts/fees-register-api:latest
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://cmc-postgres:5432/fees_register"
      SPRING_DATASOURCE_USERNAME: fees_register
      SPRING_DATASOURCE_PASSWORD: fees_register
      SPRING_LIQUIBASE_ENABLED: true
      ENABLE_FEE_LOADER: true

payment-api:
  java:
    releaseNameOverride: payment-api
    image: hmcts.azurecr.io/hmcts/payment-api:latest
    environment:
      AUTH_PROVIDER_SERVICE_CLIENT_BASEURL: http://rpe-service-auth-provider
      FEES_REGISTER_URL: http://fees-register-api
      SPRING_DATASOURCE_URL: "jdbc:postgresql://cmc-postgres:5432/payment_api"
      SPRING_DATASOURCE_USERNAME: payment-api
      SPRING_LIQUIBASE_ENABLED: true

rpe-service-auth-provider:
  java:
    releaseNameOverride: rpe-service-auth-provider
    image: hmcts.azurecr.io/hmcts/rpe-service-auth-provider:latest

postgresql:
  resources:
    requests:
      cpu: 25m
  initdbScripts:
    init.sql: |-
      CREATE USER claimstore WITH PASSWORD 'claimstore';
      CREATE DATABASE claimstore WITH OWNER = claimstore ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE USER cmc WITH PASSWORD 'cmc';
      CREATE DATABASE cmc WITH OWNER = cmc ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE USER features WITH PASSWORD 'features';
      CREATE DATABASE features WITH OWNER = features ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE USER draftstore WITH PASSWORD 'draftstore';
      CREATE DATABASE draftstore WITH OWNER = draftstore ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE USER fees_register WITH PASSWORD 'fees_register';
      CREATE DATABASE fees_register WITH OWNER = fees_register ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE USER payment_api WITH PASSWORD 'payment_api';
      CREATE DATABASE payment_api WITH OWNER = payment_api ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
  nameOverride: postgres
  persistence:
    enabled: false

cmc-claim-store:
  java:
    releaseNameOverride: cmc-claim-store
    image: hmcts.azurecr.io/hmcts/cmc-claim-store:latest
    environment:
      IDAM_API_URL: https://idam-api.aat.platform.hmcts.net
      IDAM_S2S_AUTH_URL: http://rpe-service-auth-provider
      PDF_SERVICE_URL: http://cmc-pdf-service
      SEND_LETTER_URL: false
      DOCUMENT_MANAGEMENT_URL: false
      CLAIM_STORE_DB_HOST: cmc-postgres
      CMC_DB_HOST: cmc-postgres
      FRONTEND_BASE_URL: https://${DEMO_CMC_FQDN}
      RESPOND_TO_CLAIM_URL: https://${DEMO_CMC_FQDN}/first-contact/start

cmc-citizen-frontend:
  nodejs:
    releaseNameOverride: cmc-citizen-frontend
    image: hmcts.azurecr.io/hmcts/cmc-citizen-frontend:latest
    readinessDelay: 90                        # claim-store will start much slower
    livenessDelay: 90                         # claim-store will start much slower
    registerAdditionalDns:
      enabled: false
    environment:
      IDAM_API_URL: https://idam-api.aat.platform.hmcts.net
      IDAM_URL: https://idam-api.aat.platform.hmcts.net
      IDAM_AUTHENTICATION_WEB_URL: https://idam-web-public.aat.platform.hmcts.net
      FEATURE_TOGGLES_API_URL: http://ftr-tgl-api
      CLAIM_STORE_URL: http://cmc-claim-store
      IDAM_S2S_AUTH: http://rpe-service-auth-provider
      S2S_URL: http://rpe-service-auth-provider
      IDAM_S2S_AUTH_URL: http://rpe-service-auth-provider
      PAY_URL: http://payment-api
      FEES_URL: http://fees-register-api
      DRAFT_STORE_URL: http://draft-store-service
  rpe-feature-toggle-api:
    releaseNameOverride: ftr-tgl-api
    importer:
      oneoff:
        command: /scripts/add-weighted-toggle.sh cmc_admissions 'CMC admissions' '1.0' ${ADMIN_USERNAME_TEST} ${ADMIN_PASSWORD_TEST} &&
          /scripts/add-toggle.sh cmc_defence_reminders 'CMC defence reminders' false ${ADMIN_USERNAME_TEST} ${ADMIN_PASSWORD_TEST}
    java:
      releaseNameOverride: ftr-tgl-api
      environment:
        FEATURES_DB_HOST: cmc-postgres
