tags:
  cmc-claim-store-postgresql-pod: false # claim-store chart
  cmc-citizen-frontend-pod: false       # claim-store chart
  cmc-ccd-stack: true                   # claim-store chart
  idam-pr: false                        # manually configure whitelists in IDAM until IDAM here
  ccd-idam-pr: false                    # manually configure whitelists in IDAM until IDAM here
  rpe-feature-toggle-api-pod: true      # citizen-frontend dep
  postgresql-pod: false                 # any chart specific postgres
  blobstorage: false                    # blob storage for dm-store

### CMC SERVICES ###
cmc-claim-store:
  java:
    image: hmcts.azurecr.io/hmcts/cmc-claim-store:latest
    keyVaults:
    environment:
      CLAIM_STORE_DB_USERNAME: hmcts
      CLAIM_STORE_DB_PASSWORD: hmcts
      CMC_DB_USERNAME: hmcts
      CMC_DB_PASSWORD: hmcts
  ccd:
    adminWeb:
      enabled: true
      environment:
        NODE_TLS_REJECT_UNAUTHORIZED: 0
    caseManagementWeb:
      enabled: true
      environment:
        NODE_TLS_REJECT_UNAUTHORIZED: 0
    importer:
      userprofile:
        enabled: true
        jurisdictions:
          - CMC
        users:
          - civilmoneyclaims+ccd@gmail.com|CMC|MoneyClaimCase|open
        userProfileDatabasePort: 5432
        userProfileDatabaseUser: hmcts
        userProfileDatabasePassword: hmcts
        userProfileDatabaseName: user-profile
      definition:
        enabled: true
        importerUsername: ccd-importer@server.net
        importerPassword: Password12
        image: hmcts.azurecr.io/hmcts/cmc-ccd-definition-importer:1.2.6
        definitionFilename: cmc-ccd.xlsx
        userRoles:
          - citizen
          - caseworker-cmc
          - caseworker-cmc-solicitor
          - caseworker-cmc-systemupdate
          - letter-holder
          - caseworker-autotest1
          - caseworker-cmc-anonymouscitizen

cmc-citizen-frontend:
  nodejs:
    image: hmcts.azurecr.io/hmcts/cmc-citizen-frontend:latest
    keyVaults:
    environment:
      IDAM_S2S_TOTP_SECRET: AAAAAAAAAAAAAAAA
  rpe-feature-toggle-api:
    java:
      keyVaults:
      environment:
        FEATURES_DB_NAME: features
        FEATURES_DB_USER_NAME: hmcts
        FEATURES_DB_PASSWORD: hmcts
        ADMIN_USERNAME_TEST: admin@example.com
        ADMIN_PASSWORD_TEST: Password
        EDITOR_USERNAME_TEST: editor@example.com
        EDITOR_PASSWORD_TEST: Password
    importer:
      adminUsername: admin@example.com
      adminPassword: Password
      cron:
        enabled: false
      oneoff:
        command: /scripts/add-weighted-toggle.sh cmc_admissions 'CMC admissions' '1.0' &&
          /scripts/add-weighted-toggle.sh cmc_directions_questionnaire 'CMC Directions Questionnaire' '1.0' &&
          /scripts/add-weighted-toggle.sh cmc_mediation_pilot 'CMC Mediation Pilot' '0.1' &&
          /scripts/add-toggle.sh cmc_defence_reminders 'CMC defence reminders' false
        enabled: true
        permissions: cmc-new-features-consent-given
########################

##### DEPENDENCIES #####
rpe-send-letter-service:
  java:
    image: hmcts.azurecr.io/hmcts/rpe-send-letter-service:latest
    keyVaults:
    environment:
      FILE_CLEANUP_ENABLED: true
      LETTER_TRACKING_DB_CONN_OPTIONS: ""
      LETTER_TRACKING_DB_NAME: send_letter
      LETTER_TRACKING_DB_USER_NAME: "hmcts"
      LETTER_TRACKING_DB_PASSWORD: "hmcts"

dm-store:
  java:
    image: hmcts.azurecr.io/hmcts/dm-store:latest
    secrets:
      STORAGE_ACCOUNT_NAME:
        disabled: true
      STORAGE_ACCOUNT_KEY:
        disabled: true
      STORAGE_CONTAINER_DOCUMENT_CONTAINER_NAME:
        disabled: true
    keyVaults:
    environment:
      ENABLE_DB_MIGRATE: 'true'
      ENABLE_TTL: 'false'
      SPRING_DATASOURCE_USERNAME: hmcts
      SPRING_DATASOURCE_PASSWORD: hmcts
      ENABLE_AZURE_STORAGE_CONTAINER: 'false'
      POSTGRES_STORAGE_ENABLED: 'true'
      STORAGEACCOUNT_PRIMARY_CONNECTION_STRING: 'DefaultEndpointsProtocol=https;AccountName=AAAAAAAAAAAAAAAA;AccountKey=AAAAAAAAAAAAAAAA;EndpointSuffix=core.windows.net'

cmc-pdf-service:
  java:
    image: hmcts.azurecr.io/hmcts/cmc-pdf-service:latest
    keyVaults:

draft-store-service:
  java:
    image: hmcts.azurecr.io/hmcts/draft-store-service:latest
    keyVaults:
    environment:
      DRAFT_STORE_DB_NAME: draftstore
      DRAFT_STORE_DB_PORT: '5432'
      DRAFT_STORE_DB_USER_NAME: hmcts
      RUN_DB_MIGRATION_ON_STARTUP: 'true'
      DRAFT_STORE_DB_PASSWORD: hmcts

fees-register-api:
  java:
    image: hmcts.azurecr.io/hmcts/fees-register-api:latest
    keyVaults:
    environment:
      SPRING_DATASOURCE_USERNAME: hmcts
      SPRING_DATASOURCE_PASSWORD: hmcts
      SPRING_LIQUIBASE_ENABLED: true
      ENABLE_FEE_LOADER: true

payment-api:
  java:
    image: hmcts.azurecr.io/hmcts/payment-api:latest
    keyVaults:
    environment:
      SPRING_DATASOURCE_USERNAME: hmcts
      SPRING_DATASOURCE_PASSWORD: hmcts
      SPRING_LIQUIBASE_ENABLED: true

rpe-service-auth-provider:
  java:
    image: hmcts.azurecr.io/hmcts/rpe-service-auth-provider:latest
    keyVaults:
    environment:
      TESTING_SUPPORT_ENABLED: 'true'
      MICROSERVICEKEYS_CMC: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_CMC_CLAIM_SUBMIT_API: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_CMC_LEGAL_FRONTEND: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_CMC_CLAIM_STORE: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_EM_GW: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_CCD_DATA: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_CCD_DEFINITION: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_CCD_GATEWAY: AAAAAAAAAAAAAAAA
      MICROSERVICEKEYS_DG_DOCASSEMBLY_API: AAAAAAAAAAAAAAAA

postgresql:
  resources:
    requests:
      cpu: 25m
  initdbScripts:
    init.sql: |-
      CREATE DATABASE "claimstore" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "cmc" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "features" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "draftstore" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "fees_register" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "payment_api" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "evidence" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "send_letter" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "data-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
      CREATE DATABASE "definition-store" WITH OWNER = hmcts ENCODING = 'UTF-8' CONNECTION LIMIT = -1;
  postgresqlUsername: hmcts
  postgresqlPassword: hmcts
  postgresqlDatabase: user-profile
  persistence:
    enabled: false
########################