global:
  environment:   "aat"
  idamApiUrl:    "https://idam-api.aat.platform.hmcts.net"
  idamWebUrl:    "https://idam-web-public.aat.platform.hmcts.net"
  pdfServiceUrl: "http://cmc-pdf-service-aat.service.core-compute-aat.internal"
  sendLetterUrl: "http://rpe-send-letter-service-aat.service.core-compute-aat.internal"
  documentManagementUrl: "http://dm-store-aat.service.core-compute-aat.internal"
  ccdCaseDataApiUrl: "http://ccd-data-store-api-aat.service.core-compute-aat.internal"
  s2sAuthUrl: "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
  draftStoreUrl: "http://draft-store-service-aat.service.core-compute-aat.internal"
  paymentUrl: "http://payment-api-aat.service.core-compute-aat.internal"
  feesUrl: "http://fees-register-api-aat.service.core-compute-aat.internal"

### CMC SERVICES ###
cmc-claim-store:
  java:
    releaseNameOverride: "cmc-preview-claimstore"
    secrets:
      GOV_NOTIFY_API_KEY:
        secretRef: notify-api-key
        key: key
      OAUTH2_CLIENT_SECRET:
        secretRef: oauth-client-secret
        key: key
      IDAM_CASEWORKER_ANONYMOUS_USERNAME:
        secretRef: anonymous-caseworker-username
        key: key
      IDAM_CASEWORKER_ANONYMOUS_PASSWORD:
        secretRef: anonymous-caseworker-password
        key: key
      IDAM_CASEWORKER_SYSTEM_USERNAME:
        secretRef: system-update-username
        key: key
      IDAM_CASEWORKER_SYSTEM_PASSWORD:
        secretRef: system-update-password
        key: key
    environment:
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025
      CLAIM_STORE_DB_HOST: "cmc-preview-postgres"
      CMC_DB_HOST: "cmc-preview-postgres"
      FEATURE_TOGGLES_DIRECTIONS_QUESTIONNAIRE_ENABLED: true
      FEATURE_TOGGLES_SAVE_CLAIM_STATE_ENABLED: true
      IDAM_API_URL: '{{ .Values.global.idamApiUrl }}'
      IDAM_S2S_AUTH_URL: '{{ .Values.global.s2sAuthUrl }}'
      FRONTEND_BASE_URL: "https://cmc-preview-citizen-frontend.service.core-compute-preview.internal"
      RESPOND_TO_CLAIM_URL: "https://cmc-preview-citizen-frontend.service.core-compute-preview.internal/first-contact/start"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST: mailhog
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: false
      APPINSIGHTS_INSTRUMENTATIONKEY: 00000000-0000-0000-0000-000000000000
      CORE_CASE_DATA_API_URL: '{{ .Values.global.ccdCaseDataApiUrl }}'
      PDF_SERVICE_URL: '{{ .Values.global.pdfServiceUrl }}'
      SEND_LETTER_URL: '{{ .Values.global.sendLetterUrl }}'
      DOCUMENT_MANAGEMENT_URL: '{{ .Values.global.documentManagementUrl }}'
      LIVE_SUPPORT_RECIPIENT: civilmoneyclaims+live-support-int-tests@gmail.com
      LIVE_SUPPORT_SENDER: noreply@reform.hmcts.net
      PAY_URL: '{{ .Values.global.paymentUrl }}'
      FEES_URL: '{{ .Values.global.feesUrl }}'

cmc-citizen-frontend:
  nodejs:
    ingressHost: "cmc-preview-citizen-frontend.service.core-compute-preview.internal"
    releaseNameOverride: "cmc-preview-citizen-web"
    memoryRequests: 512Mi
    memoryLimits: 1024Mi
    secrets:
      OAUTH_CLIENT_SECRET:
        secretRef: citizen-oauth-client-secret
        key: key
    environment:
      IDAM_API_URL: '{{ .Values.global.idamApiUrl }}'
      IDAM_AUTHENTICATION_WEB_URL: '{{ .Values.global.idamWebUrl }}'
      CLAIM_STORE_URL: "http://cmc-preview-claimstore"
      FEATURE_TOGGLES_API_URL: "http://cmc-preview-ftrtgl"
      IDAM_S2S_AUTH: '{{ .Values.global.s2sAuthUrl }}'
      DRAFT_STORE_URL: '{{ .Values.global.draftStoreUrl }}'
      FEATURE_MEDIATION: true
      FEATURE_MEDIATION_PILOT: true
      FEATURE_DIRECTIONS_QUESTIONNAIRE: true
      FEATURE_ADMISSIONS: true
      FEATURE_INVERSION_OF_CONTROL: true
      PAY_URL: '{{ .Values.global.paymentUrl }}'
      FEES_URL: '{{ .Values.global.feesUrl }}'
  idam-pr:
    service:
      redirect_uri: "https://cmc-preview-citizen-frontend.service.core-compute-preview.internal/receiver"
  rpe-feature-toggle-api:
    importer:
      apiUrl: "http://cmc-preview-ftrtgl/api/ff4j/store/features/"
    java:
      releaseNameOverride: "cmc-preview-ftrtgl"
      environment:
        FEATURES_DB_HOST: "cmc-preview-postgres"

########################

postgresql:
  nameOverride: postgres

########################
