global:
  environment:   "aat"
  idamApiUrl:    "https://idam-api.aat.platform.hmcts.net"
  idamWebUrl:    "https://idam-web-public.aat.platform.hmcts.net"
  draftStoreUrl: "http://draft-store-service-aat.service.core-compute-aat.internal"
  s2sAuthUrl:    "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
  pdfServiceUrl: "http://cmc-pdf-service-aat.service.core-compute-aat.internal"
  paymentUrl:    "http://payment-api-aat.service.core-compute-aat.internal"
  feesUrl:       "http://fees-register-api-aat.service.core-compute-aat.internal"
  sendLetterUrl: "http://rpe-send-letter-service-aat.service.core-compute-aat.internal"
  documentManagementUrl: "http://dm-store-aat.service.core-compute-aat.internal"
  dgAssemblyUrl: "http://dg-docassembly-aat.service.core-compute-aat.internal"
  ccdCaseDataApiUrl: "http://ccd-data-store-api-aat.service.core-compute-aat.internal"
  postgresqlHost: "cmc-preview-postgres"

### CMC SERVICES ###
cmc-claim-store:
  java:
    releaseNameOverride: "cmc-preview-claimstore"
    secrets:
      GOV_NOTIFY_API_KEY:
        secretRef: notify-api-key
        key: key
      OAUTH2_CLIENT_SECRET:
        secretRef: oauth-client-secret
        key: key
      IDAM_CASEWORKER_ANONYMOUS_USERNAME:
        secretRef: anonymous-caseworker-username
        key: key
      IDAM_CASEWORKER_ANONYMOUS_PASSWORD:
        secretRef: anonymous-caseworker-password
        key: key
      IDAM_CASEWORKER_SYSTEM_USERNAME:
        secretRef: system-update-username
        key: key
      IDAM_CASEWORKER_SYSTEM_PASSWORD:
        secretRef: system-update-password
        key: key

cmc-citizen-frontend:
  nodejs:
    ingressHost: 'cmc-preview-citizen-frontend.service.core-compute-preview.internal'
    releaseNameOverride: 'cmc-preview-citizen-web'
    memoryRequests: 512Mi
    memoryLimits: 1024Mi
    secrets:
      OAUTH_CLIENT_SECRET:
        secretRef: citizen-oauth-client-secret
        key: key
  idam-pr:
    service:
      redirect_uri: "https://cmc-preview-citizen-frontend.service.core-compute-preview.internal/receiver"
  rpe-feature-toggle-api:
    importer:
      apiUrl: "http://cmc-preview-ftrtgl/api/ff4j/store/features/"
    java:
      releaseNameOverride: "cmc-preview-ftrtgl"
      environment:
        FEATURES_DB_HOST: "cmc-preview-postgres"

########################

postgresql:
  nameOverride: postgres

########################
