global:
  environment:   "aat"
  idamApiUrl:    "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
  idamWebUrl:    "https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net"
  pdfServiceUrl: "http://cmc-pdf-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
  sendLetterUrl: "http://rpe-send-letter-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
  documentManagementUrl: "http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
  ccdCaseDataApiUrl: "http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
  s2sAuthUrl: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
  draftStoreUrl: "http://draft-store-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"


### CMC SERVICES ###
cmc-claim-store:
  java:
    releaseNameOverride: "{{ .Release.Name }}-claimstore"
    secrets:
      GOV_NOTIFY_API_KEY:
        secretRef: notify-api-key
        key: key
      OAUTH2_CLIENT_SECRET:
        secretRef: oauth-client-secret
        key: key
      IDAM_CASEWORKER_ANONYMOUS_USERNAME:
        secretRef: anonymous-caseworker-username
        key: key
      IDAM_CASEWORKER_ANONYMOUS_PASSWORD:
        secretRef: anonymous-caseworker-password
        key: key
      IDAM_CASEWORKER_SYSTEM_USERNAME:
        secretRef: system-update-username
        key: key
      IDAM_CASEWORKER_SYSTEM_PASSWORD:
        secretRef: system-update-password
        key: key
    environment:
      SPRING_MAIL_HOST: mailhog
      SPRING_MAIL_PORT: 1025
      CLAIM_STORE_DB_HOST: "http://{{ .Release.Name }}-postgres"
      CMC_DB_HOST: "http://{{ .Release.Name }}-postgres"
      FEATURE_TOGGLES_DIRECTIONS_QUESTIONNAIRE_ENABLED: true
      FEATURE_TOGGLES_SAVE_CLAIM_STATE_ENABLED: true
      IDAM_API_URL: '{{ .Values.global.idamApiUrl }}'
      IDAM_S2S_AUTH_URL: '{{ .Values.global.s2sAuthUrl }}'
      FRONTEND_BASE_URL: "https://{{ .Release.Name }}-citizen-frontend.service.core-compute-preview.internal"
      RESPOND_TO_CLAIM_URL: "https://{{ .Release.Name }}-citizen-frontend.service.core-compute-preview.internal/first-contact/start"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST: mailhog
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: false
      APPINSIGHTS_INSTRUMENTATIONKEY: 00000000-0000-0000-0000-000000000000
      CORE_CASE_DATA_API_URL: '{{ .Values.global.ccdCaseDataApiUrl }}'
      PDF_SERVICE_URL: '{{ .Values.global.pdfServiceUrl }}'
      SEND_LETTER_URL: '{{ .Values.global.sendLetterUrl }}'
      DOCUMENT_MANAGEMENT_URL: '{{ .Values.global.documentManagementUrl }}'
      PAY_URL: false
      FEES_URL: false

cmc-citizen-frontend:
  nodejs:
    ingressHost: "{{ .Release.Name }}-citizen-frontend.service.core-compute-preview.internal"
    memoryRequests: 512Mi
    memoryLimits: 1024Mi
    releaseNameOverride: "{{ .Release.Name }}-citizen-web"
    secrets:
      OAUTH_CLIENT_SECRET:
        secretRef: citizen-oauth-client-secret
        key: key
    environment:
      IDAM_API_URL: '{{ .Values.global.idamApiUrl }}'
      IDAM_AUTHENTICATION_WEB_URL: '{{ .Values.global.idamWebUrl }}'
      CLAIM_STORE_URL: "http://{{ .Release.Name }}-claimstore"
      FEATURE_TOGGLES_API_URL: "http://{{ .Release.Name }}-ftrtgl"
      IDAM_S2S_AUTH: '{{ .Values.global.s2sAuthUrl }}'
      DRAFT_STORE_URL: '{{ .Values.global.draftStoreUrl }}'
      FEATURE_MEDIATION: true
      FEATURE_MEDIATION_PILOT: true
      FEATURE_DIRECTIONS_QUESTIONNAIRE: true
      FEATURE_ADMISSIONS: true
      FEATURE_INVERSION_OF_CONTROL: true
      PAY_URL: false
      FEES_URL: false

  idam-pr:
    service:
      redirect_uri: "https://{{ .Release.Name }}-citizen-frontend.service.core-compute-preview.internal/receiver"
  rpe-feature-toggle-api:
    importer:
      apiUrl: "http://{{ .Release.Name }}-ftrtgl/api/ff4j/store/features/"
    java:
      releaseNameOverride: "{{ .Release.Name }}-ftrtgl"
      environment:
        FEATURES_DB_HOST: "http://{{ .Release.Name }}-postgres"

########################

postgresql:
  nameOverride: postgres

########################
